# Generated by Django 3.0.6 on 2020-07-13 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='porder_id',
            new_name='order_id',
        ),
    ]
